name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it. Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the pain point or limitation you're running into.
      placeholder: I'm frustrated when…
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: It would be great if…
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Which area does this relate to?
      options:
        - Home / Widgets
        - App Grid
        - Browser
        - Navigation / D-pad UX
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, links, or anything else that helps.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues and this has not been requested before
          required: true
